-- Migration 002: create public Storage bucket for onboarding file uploads
-- Run this in Supabase SQL Editor → then enable RLS on storage.objects if not already.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'onboarding-files',
  'onboarding-files',
  true,
  52428800,   -- 50 MB per file
  ARRAY[
    'image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/svg+xml',
    'application/pdf',
    'video/mp4', 'video/quicktime'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- Public read (files served directly by Supabase CDN)
CREATE POLICY "onboarding_files_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'onboarding-files');

-- Allow upload via signed URLs generated by the backend (service_role)
-- Anon users can INSERT only when they have a valid signed URL token
CREATE POLICY "onboarding_files_signed_upload"
  ON storage.objects FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'onboarding-files');
